name: deploy-website

# Only run this when the main branch changes
on:
  pull_request:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt


    # Build the book
    - name: Build the site
      run: |
        make dirhtml

    # If we've pushed to main, push the book's HTML to github-pages
    - if: ${{ github.ref == 'refs/heads/main' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.5.9
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/dirhtml
        cname: ml4sts.com
